### ISSUE TITLE
White Window Refresh and menu failure

### ISSUE THREAD

**Issue by destroyer667** [otya128/winevdm#852]
White Window Refresh:

Several windows are opened in my program.
Each time a window opens, the rest of the program turns white.
I have to minimize and restore the entire program only then all windows are visible.

menu failure:

None of the menu items has a function even under file -> exit nothing happens
already when starting the program several errors appear in the console

![Unbenannt22](https://user-images.githubusercontent.com/73582776/104896532-87d81e00-5977-11eb-8771-d38cbebc7e77.png)

**Comment by cracyc** [comment]
There's an outside possibility that https://ci.appveyor.com/api/buildjobs/mia5k732h709bd0n/artifacts/otvdm-master-1913.zip will help.  If not a trace is needed.

**Comment by destroyer667** [comment]
sorry but i am already using 1913 forgot to update the picture. No error was fixed by this.

Console:

![console programm opened](https://user-images.githubusercontent.com/73582776/105001866-b2d27880-5a30-11eb-8851-8183a52d005b.png)

white window failure:

If Programm opened:
![programm open](https://user-images.githubusercontent.com/73582776/105001930-cbdb2980-5a30-11eb-943d-89d7f0eebce9.png)

program minimized and restored:
![programm minimized an resized](https://user-images.githubusercontent.com/73582776/105002040-f88f4100-5a30-11eb-9b1e-d41936f30011.png)

menu failure:

![menu failure](https://user-images.githubusercontent.com/73582776/105002269-44da8100-5a31-11eb-9eab-23be64ef63ab.png)

This and all other menus are completely without function or response

**Comment by destroyer667** [comment]
> There's an outside possibility that https://ci.appveyor.com/api/buildjobs/mia5k732h709bd0n/artifacts/otvdm-master-1913.zip will help. If not a trace is needed.

see over

**Comment by cracyc** [comment]
There's no way from those pictures to determine what is wrong.  Unless there's a trial version or something so I can do it myself, I need a trace to have any way to understand what is happening.

**Comment by destroyer667** [comment]
> There's no way from those pictures to determine what is wrong. Unless there's a trial version or something so I can do it myself, I need a trace to have any way to understand what is happening.
> 
> Edit: That appears to be running in msaccess 2.0 which shows similar behavior for the windows, not the menus though.

okay i will see if i can send you a version of the program in the next few days

**Comment by destroyer667** [comment]
Where can I send the program?
This is a licensed program, so I would like to delete it when it is no longer needed.
would only reluctantly put it here publicly pure.

**Comment by destroyer667** [comment]
> There's no way from those pictures to determine what is wrong. Unless there's a trial version or something so I can do it myself, I need a trace to have any way to understand what is happening.
> 
> Edit: That appears to be running in msaccess 2.0 which shows similar behavior for the windows, not the menus though.


[DEMO.zip](https://github.com/otya128/winevdm/files/5856371/DEMO.zip)

here is a "demo" of the program
It only works from drive "E" and must be started with the Toffi.Ink.
I delete this link on 25.01.2021.

**Comment by cracyc** [comment]
Go ahead and delete it if you want.

**Comment by cracyc** [comment]
https://ci.appveyor.com/project/otya128/winevdm/builds/37416255/job/d85r9aphppmeu5w2/artifacts adds better support for sendkeys which that program seems to use a lot.

**Comment by destroyer667** [comment]
> https://ci.appveyor.com/project/otya128/winevdm/builds/37416255/job/d85r9aphppmeu5w2/artifacts adds better support for sendkeys which that program seems to use a lot.

update:

I use dev1923 on Windows 10.
The errors have remained but now I can no longer open a program under Windows 10 by double-clicking but it opens the properties window and the standard Windows 10 key combinations, for example, to copy no longer work.

**Comment by cracyc** [comment]
1925 doesn't have any of the changes.  With 1923, for me, the window paint problem is fixed and the menu items work.  The ctrl-c, ctrl-v combinations don't work in the program even in ntvdm but I suspect you mean they don't work outside of the program.  This can happen if sendkeys causes the windows key state to get out of sync.  I'd need to know what function you do in the program that causes the problem.

**Comment by destroyer667** [comment]
I will test it again today on another PC. It doesn't seem to work on my PC running Windows 10 version 2004 (build 19041.746). Whenever a new popup window opens, all the others turn white. Also, I still can't use the menu items at the top. So none of the menu items work for me even quitting the program is not possible via the menu.
